spring:
  application:
    name: account-service
server:
  port: 8800
eureka:
  instance:
    instance-id: account001
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
